### ISSUE TITLE
Npm install issue

### ISSUE THREAD

**Issue by ghaiat** [gdi2290/angular2-hmr#12]
Hello
I m having the following issue when trying to install 0.6.0:

````typings ERR! message Unable to resolve Typings dependencies
typings ERR! caused by Unable to find "typings.json" from "/Users/xxxx/Documents/Phonegap/yo-ui-web/node_modules/angular2-hmr"````

**Comment by Kikketer** [comment]
Please get this fixed, this really irritates me that dependencies can bork an entire library (like Angular 2) because it's not build in an environment that isn't local.  Every time I run into this (not the first time with Angular 2) I get inspired to drop NPM completely.

**Comment by TheLarkInn** [comment]
@gdi2290 is this an easy fix? Typings related? LMK if you need help with this.

**Comment by gdi2290** [comment]
is this still an issue? we don't have postinstall anymore

**Comment by TheLarkInn** [comment]
Haven't tested it myself, was just lurking in all your repoz.

**Comment by gdi2290** [comment]
I'll close this but if someone has this error please reopen the issue
