### ISSUE TITLE
Use with Webpack Dev middleware?

### ISSUE THREAD

**Issue by pierre-hilt** [gdi2290/angular2-hmr#14]
Hello,

Is it possible to use angular2-hmr with webpack dev middleware? (Not only webpack-dev-server).

it seems that [module.hot](https://github.com/gdi2290/angular2-hmr/blob/master/src/webpack-hmr.ts#L14) is undefined when using middleware (even when passing --hot).

server.js:

```
var webpack = require('webpack');
var webpackDevMiddleware = require('webpack-dev-middleware');
var webpackHotMiddleware = require('webpack-hot-middleware');
var request = require('request');
var bodyParser = require('body-parser');
var config = require('./config/webpack.dev');

var app = new (require('express'))();
var port = 3000;

var compiler = webpack(config);
app.use(webpackDevMiddleware(compiler, { noInfo: true, publicPath: config.output.publicPath }));
app.use(webpackHotMiddleware(compiler));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.get('/', function(req, res) {
  res.sendFile(__dirname + '/static/index.html')
});

app.listen(port, function(error) {
  if (error) {
    console.error(error)
  } else {
    console.info('==> Listening on port %s. Open up http://localhost:%s/ in your browser.', port, port)
  }
});
```

Error in chrome:
`Warning: please use webpack hot flag`

**Comment by pierre-hilt** [comment]
OK, I found the problem. I forgot to add webpack-hot-middleware/client in the entries and webpack.HotModuleReplacementPlugin() as plugin..

It works now without any problem.

**Comment by gdi2290** [comment]
do you have an example of an express server with all the features of webpack-dev-server?

**Comment by blyscuit** [comment]
I use this set up for my project https://github.com/vuejs-templates/webpack and faced the same problem. `var path = require('path');
var express = require('express');
var webpack = require('webpack');
var config = require('../config');
var opn = require('opn');
var proxyMiddleware = require('http-proxy-middleware');
var webpackConfig = require('./webpack.dev.conf');

var mongodb = require('mongodb');
var MongoClient = mongodb.MongoClient;
var bodyParser = require('body-parser');

var url = 'mongodb://localhost:27017/infosys';

// default port where dev server listens for incoming traffic
var port = process.env.PORT || config.dev.port;
// Define HTTP proxies to your custom API backend
// https://github.com/chimurai/http-proxy-middleware
var proxyTable = config.dev.proxyTable;

var app = express();

var compiler = webpack(webpackConfig);

// proxy api requests
Object.keys(proxyTable).forEach(function (context) {
  var options = proxyTable[context];
  if (typeof options === 'string') {
    options = { target: options }
  }
  app.use(proxyMiddleware(context, options))
})

// var compiler = webpack(config);
var webpackDevMiddleware = require('webpack-dev-middleware');
var webpackHotMiddleware = require('webpack-hot-middleware');
app.use(webpackDevMiddleware(compiler));
app.use(webpackHotMiddleware(compiler));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
// serve pure static assets
var staticPath = path.posix.join(config.dev.assetsPublicPath, config.dev.assetsSubDirectory)
app.use(staticPath, express.static('./static'))

module.exports = app.listen(port, function (err) {
  if (err) {
    console.log(err);
    return
  }
  var uri = 'http://localhost:' + port;
  console.log('Listening at ' + uri + '\n');
  opn(uri)
});`
I remove the provided middlewares and use the code as in the question. It is now working.
