### ISSUE TITLE
Exception Uncaught TypeError: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [gdi2290/angular2-hmr#16]
I tried to implement the code in another Angular 2 project. Although I think I included all the necessary code I get 'Uncaught TypeError: Cannot read property 'location' of undefined' in chrome console when HMR tries to check/update the code.

Stacktrace:
webpack-hmr.js:73 Uncaught TypeError: Cannot read property 'location' of undefined(anonymous function) @ webpack-hmr.js:73
hotApply @ bootstrap 1406622…:456
hotUpdateDownloaded @ bootstrap 1406622…:326
hotAddUpdateChunk @ bootstrap 1406622…:306webpack
HotUpdateCallback @ bootstrap 1406622…:2
(anonymous function) @ VM1024 0.1406622….hot-update.js:1

Any ideas?

**Comment by gdi2290** [comment]
what version of Angular 2 are you using?

**Comment by LanderBeeuwsaert** [comment]
RC1 with the deprecated router (from the beta).

**Comment by gdi2290** [comment]
are you returning the `bootstrap` function in your main function
```typescript
function main(initialHMRstate) {
  // you must return
  return bootstrap(App, []);
}
/*
 * Hot Module Reload
 * experimental version by @gdi2290
 */
if (isDevelopment) {
  // activate hot module reload
  let ngHmr = require('angular2-hmr');
  ngHmr.hotModuleReplacement(main, module); // pass the main function
} else {
  // bootstrap when document is ready
  document.addEventListener('DOMContentLoaded', () => main());
}
```

**Comment by LanderBeeuwsaert** [comment]
Jep, I'll copy some of the code below:
in main.ts:
const providers: any[] = [
  AUTH_PROVIDERS,
  FIREBASE_APP_PROVIDERS,
  ROUTER_PROVIDERS,
  TASK_PROVIDERS,
  APP_PROVIDERS
];


/* ORIGINAL
bootstrap(App, providers)
  .then((appRef: ComponentRef<App>) => {
    AuthRouteHelper.injector(appRef.injector as ReflectiveInjector);
  })
.catch((error: Error) => console.error(error));
*/

/*WITH HMR*/
export function main(initialHmrState?: any): Promise<any> {

  return bootstrap(App, providers)
      .then((appRef: ComponentRef<App>) => {
        AuthRouteHelper.injector(appRef.injector as ReflectiveInjector);
      })
      .catch(err => console.error(err));
}

/*
 * Hot Module Reload
 * experimental version by @gdi2290
 */
let ngHmr = require('angular2-hmr');
ngHmr.hotModuleReplacement(main, module);

in package.json:
"dev": "cross-env NODE_ENV=development webpack-dev-server --progress --hot --inline --watch",

**Comment by LanderBeeuwsaert** [comment]
If you want I can provide a zip from the project...

**Comment by gdi2290** [comment]
you should always return in promises
you have a `.then` so you need to return the componentRef

**Comment by LanderBeeuwsaert** [comment]
Indeed, that solved the problem. Thanks!
