### ISSUE TITLE
reduce over default state with current state

### ISSUE THREAD

**Issue by gdi2290** [gdi2290/angular2-hmr#3]
reduce over default state with current state

**Comment by MarkPieszak** [comment]
Yo brotha, you got the HMR working for ng2?? @gdi2290 
Loaded up your ng2 starter and saw you added application state and it's holding it :)

What was the trick / missing ??

**Comment by gdi2290** [comment]
the trick was using a proxy to maintain state during the refresh. I think this works now even though it was pretty hacky
