### ISSUE TITLE
COMPONENT_REF.injector.getOptional is not a function

### ISSUE THREAD

**Issue by anslzo** [gdi2290/angular2-hmr#6]
When using the latest version of [Angular-Class starter kit](https://github.com/AngularClass/angular2-webpack-starter), I get an error whenever a change is made and HMR fails to work. It fails on [this line](https://github.com/gdi2290/angular2-hmr/blob/master/src/webpack-hmr.ts#L91) If I modify the code slightly to 

    let appState = TOKEN;
    if(COMPONENT_REF.injector.getOptional) {
      appState = COMPONENT_REF.injector.getOptional(TOKEN)
    }

Then the reloading will work, but I will have two components since the later line with `COMPONENT_REF.dispose();` fails. 

So I'm not sure why it's not properly grabbing the component, but I do know that it's not working properly.
This seems to affect v0.5.5.

This issue occurs when I run 

`npm run server:dev:hmr`

and then modify the home.ts source to change some words in the template.

**Comment by leon** [comment]
It's because in angular 2.0.0-beta.16 they changed the api around a bit.

https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

**Comment by gdi2290** [comment]
this should be fixed but now the repo only works with rc1
