### ISSUE TITLE
Update to Angular beta 17

### ISSUE THREAD

**Issue by rarakiroa** [gdi2290/angular2-hmr#8]
Beta 17 is out, at least dependencies in package.json need to be changed.

**Comment by TobiasKrogh** [comment]
did a manual check with angular2 beta 17 and rxjs beta 6 using the current implementation... worked quite well... updating the peerDependencies to also support beta 17 would be great

**Comment by TobiasKrogh** [comment]
https://github.com/gdi2290/angular2-hmr/commit/9f30cf2a2056caf6e1cb4121434c151538357ec1 works fine for me

**Comment by rarakiroa** [comment]
For me as well, thanks
